# Generated by Django 5.2 on 2025-05-01 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0002_user_delete_apple'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_num', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('billing_company', models.CharField(max_length=100)),
                ('ice', models.CharField(blank=True, max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(max_length=50)),
                ('point_attach', models.CharField(default='TAMANAR', max_length=100)),
                ('lieu_intervention', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('perimetre', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe_assistance', models.CharField(default='WAFA IMA ASSISTANCE', max_length=100)),
                ('ref_dossier', models.CharField(max_length=50)),
                ('assure', models.CharField(max_length=100)),
                ('date_intervention', models.DateField()),
                ('evenement', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('point_attach', models.CharField(default='TAMANAR', max_length=100)),
                ('lieu_intervention', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('cout_prestation_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='impayé', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicule', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('pompiste', models.CharField(blank=True, max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
