# Generated by Django 5.2 on 2025-05-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='societe_assistance',
            field=models.CharField(choices=[('MAI', 'MAI'), ('IMA', 'IMA'), ('RMA', 'RMA')], default='MAI', max_length=10),
        ),
    ]
