# Generated by Django 5.2 on 2025-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0006_alter_facture_user_alter_intervention_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['-date_intervention']},
        ),
        migrations.AlterModelOptions(
            name='suivicarburant',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_num',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='evenement',
            field=models.CharField(choices=[('Remorquage Interurbain', 'Remorquage Interurbain'), ('Panne Mécanique', 'Panne Mécanique'), ('Accident', 'Accident'), ('Assistance', 'Assistance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ref_dossier',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('impayé', 'Impayé'), ('payé', 'Payé')], default='impayé', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
