# Generated by Django 5.2 on 2025-06-01 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0008_adminactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adminactionlog',
            name='record_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='facture',
            name='intervention',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='USERS.intervention'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='facture_num',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='ref_dossier',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Annulé', 'Annulé'), ('Complété', 'Complété')], default='En cours', max_length=50),
        ),
        migrations.AddField(
            model_name='intervention',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERS.groupeintervention'),
        ),
    ]
