# Generated by Django 5.2 on 2025-06-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0009_groupeintervention_adminactionlog_model_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='tva',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
