# Generated by Django 5.2 on 2025-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0010_alter_intervention_tva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='ref_dossier',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
