# Generated by Django 5.2 on 2025-06-05 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0011_alter_intervention_ref_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocieteAssistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('ice', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': "Société d'Assistance",
                'verbose_name_plural': "Sociétés d'Assistance",
            },
        ),
        migrations.RemoveField(
            model_name='facture',
            name='billing_company',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='societe_assistance',
        ),
        migrations.AddField(
            model_name='facture',
            name='billing_company_name_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='intervention',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='USERS.intervention'),
        ),
        migrations.AddField(
            model_name='facture',
            name='billing_company_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_factures', to='USERS.societeassistance'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='societe_assistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_assigned', to='USERS.societeassistance'),
        ),
    ]
