# Generated by Django 5.2 on 2025-06-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0012_societeassistance_remove_facture_billing_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=20, editable=False, max_digits=10),
        ),
    ]
