# Generated by Django 5.2 on 2025-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0014_alter_intervention_tva'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivicarburant',
            name='station',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
