# Generated by Django 5.2 on 2025-06-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0015_suivicarburant_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='factures_pdfs/'),
        ),
    ]
