# Generated by Django 5.2 on 2025-08-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0016_facture_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suivicarburant',
            old_name='station',
            new_name='smitoStation',
        ),
    ]
