# Generated by Django 5.2 on 2025-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0017_rename_station_suivicarburant_smitostation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_intervention',
            field=models.DateField(null=True),
        ),
    ]
